### ISSUE TITLE
DataGrid useStickyColumn is breaking SSR

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#2958]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Our application has server-sider rendering enabled and the latest DataGrid component is throwing an error in SSR which halts our server backend. Data hook or component should never reference the `window` object except in the `useEffect` callback.

```
[2023-05-04T07:45:52.091] [FATAL] @console/console-platform-express-setup - window is not defined ReferenceError: window is not defined
    at useStickyColumn (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/useStickyColumn.js:23:40)
    at /Users/flannanl/Git/projects-ui/node_modules/react-table/dist/react-table.development.js:1022:7
    at Array.forEach (<anonymous>)
    at useTable (/Users/flannanl/Git/projects-ui/node_modules/react-table/dist/react-table.development.js:1021:29)
    at useDatagrid (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/useDatagrid.js:32:41)
    at ProjectList (/Users/flannanl/Git/projects-ui/dist/components/ProjectList.js:344:52)
    at processChild (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
    at resolve (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToStaticMarkup (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
    at /Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/ssr.cjs:127:21
    at new Promise (<anonymous>)
    at process (/Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/ssr.cjs:125:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> Is this issue related to a specific component?

Yes, DataGrid, useStickyColumn data hook.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

SSR should work at all times.

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`@carbon/ibm-products` v1.51

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Projects

**Comment by dvesperini** [comment]
@zhanttbj any news?
