### ISSUE TITLE
NPE found in SSR

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#3655]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
We see the following NPE when doing SSR (server side rendering) with React. After doing some self debugging, the `getColTitle` has a few lines trying to do `col.Header().props.children.props` but ``col.Header().props.children` is `undefined`, causing the NPE.

```
[2023-10-20T13:52:10.575] [FATAL] @console/console-platform-express-setup - Cannot read properties of undefined (reading 'props') TypeError: Cannot read properties of undefined (reading 'props')
    at checkTitle (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/utils/getColTitle.js:24:36)
    at getColTitle (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/utils/getColTitle.js:29:89)
    at getAccessibilityProps (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridHeaderRow.js:34:40)
    at /Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridHeaderRow.js:135:8
    at Array.map (<anonymous>)
    at HeaderRow (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridHeaderRow.js:112:6)
    at /Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridHead.js:26:7
    at Array.map (<anonymous>)
    at DatagridHead (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridHead.js:23:82)
    at processChild (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:21:21
    at new Promise (<anonymous>)
    at process (/Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:19:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect no issue with SSR with the Datagrid component.

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
@carbon/ibm-products 1.59.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Projects

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by matthewgallo** [comment]
Hey @flannanl, this seems to be a duplicate of #3649. I'm taking a look at this today and will post an update on #3649 when it is fixed.
