### ISSUE TITLE
Datagrid useSelectRows extension crashes in SSR

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#4234]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When using `useSelectedRows` in Datagrid, it crashes the app in SSR.

```
[2024-02-07T12:54:42.329] [FATAL] @console/console-platform-express-setup - window is not defined ReferenceError: window is not defined
    at SelectAll (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/Datagrid/DatagridSelectAll.js:24:40)
    at processChild (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:21:21
    at new Promise (<anonymous>)
    at process (/Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:19:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Steps to reproduce the issue

- Render Datagrid with `useSelectedRows` on server side

**Comment by matthewgallo** [comment]
We merged a fix for this earlier today actually https://github.com/carbon-design-system/ibm-products/pull/4216

**Comment by flannanl** [comment]
Sure, but I need the fix in v1. Can you port the fix over there?

**Comment by matthewgallo** [comment]
Hey @flannanl, those same changes have now been applied for v1 and will be included in Tuesday's release.

**Comment by flannanl** [comment]
Verified and working. Thanks.
