### ISSUE TITLE
Datagrid useSelectAllToggle extension crashes in SSR

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#4311]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When using `useSelectAllToggle ` in Datagrid, it crashes the app in SSR.

```
[2024-02-11T21:42:44.029] [FATAL] @console/console-platform-express-setup - window is not defined ReferenceError: window is not defined
    at useAddClassNameToSelectRow (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/useSelectAllToggle.js:51:40)
    at plugin (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/useSelectAllToggle.js:30:3)
    at forEach (/Users/flannanl/Git/projects-ui/node_modules/react-table/src/hooks/useTable.js:79:5)
    at Array.forEach (<anonymous>)
    at useTable (/Users/flannanl/Git/projects-ui/node_modules/react-table/src/hooks/useTable.js:78:27)
    at useDatagrid (/Users/flannanl/Git/projects-ui/node_modules/@carbon/ibm-products/lib/components/Datagrid/useDatagrid.js:44:41)
    at SolutionList (/Users/flannanl/Git/projects-ui/src/components/SolutionList.js:694:36)
    at processChild (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToStaticMarkup (/Users/flannanl/Git/projects-ui/node_modules/react-dom/cjs/react-dom-server.node.development.js:4314:27)
    at /Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:21:21
    at new Promise (<anonymous>)
    at process (/Users/flannanl/Git/projects-ui/node_modules/@apollo/client/react/ssr/getDataFromTree.js:19:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Server side rendering Datagrid should work.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
Both v2 and v1 versions.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Projects

## Steps to reproduce the issue

- Render Datagrid with `useSelectedRows` on server side

**Comment by matthewgallo** [comment]
This has been addressed and will be included in tomorrow's release.
