### ISSUE TITLE
NPE caught in useFocusRowExpander 

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#5353]
### Package

Carbon for IBM Products

### Description

In my Datagrid, I am using `useNestedRows`. Occasionally, I am getting a NPE. I cannot consistently reproduce it. It just happens randomly.

```
TypeError: Cannot read properties of null (reading 'focus')
    at useFocusRowExpander.js:37:1
    at invokePassiveEffectCreate (react-dom.development.js:23487:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at flushPassiveEffectsImpl (react-dom.development.js:23574:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at flushPassiveEffects (react-dom.development.js:23447:1)
    at performSyncWorkOnRoot (react-dom.development.js:22269:1)
```

Looking at the code, the NPE is coming from:
```
    if (activeRow.length) {
      var rowExpander = activeRow[0].querySelector(".".concat(blockClass, "__row-expander"));
      rowExpander.focus(); <--
    }
```

Is it possible to put a NPE guard there? When this occurs, my page is blown up.

### Component(s) impacted

- Datagrid / useFocusRowExpander

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

1.72.2

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Cloud Projects

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by flannanl** [comment]
@matthewgallo Can we have this fix in v1?
